exclude: "(doc|dist)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: just fmt
        language: system
        pass_filenames: false
      - id: ruff-lint
        name: ruff-lint
        entry: just lint-fix
        language: system
        pass_filenames: false
      - id: ty
        name: ty
        entry: just typecheck
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: just test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
