# Safety Security and License Configuration file
security: # configuration for the `safety check` command
  ignore-cvss-severity-below: 0 # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL
  ignore-cvss-unknown-severity: False # True or False. We recommend you set this to False.
  ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
    70612: # Example vulnerability ID
      reason: we do not use jinja2 templates in this project # optional, for internal note purposes to communicate with your team. This reason will be reported in the Safety reports
      expires: "2024-09-01" # datetime string - date this ignore will expire, best practice to use this variable
  continue-on-vulnerability-error: True # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities
