name: Release to PyPI

on:
  # trigger the workflow on release publish or manually dispatch from the Actions tab
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv build
          uv publish --token $PYPI_TOKEN
