# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-18.04, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
          poetry-version: 1.1.13
    - name: Install dependencies
      run: |
        poetry install
    - name: Run tests
      run: |
        poetry run pytest --cov=pystatis tests
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.2]
        poetry-version: [1.1.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black . --check
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run flake8
        run: poetry run flake8 src --output-file=flake8_report.txt
      - name: Run pylint
        run: poetry run pylint src --recursive=y
      - name: Run bandit
        run: poetry run bandit -r src
      - name: Run safety
        run: poetry run safety check
      - name: Run mypy
        run: poetry run mypy src
